#include "cpp_generator.h"
#include "core/logger.h"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <iomanip>

namespace fs = std::filesystem;

namespace ue {
namespace {

std::string indent(int n) { return std::string(static_cast<size_t>(n) * 4, ' '); }

void write_banner(std::ostream& os, const std::string& title) {
    os << "// Generated by ue_sdk_gen — do not edit by hand\n";
    os << "// " << title << "\n\n";
    os << "#pragma once\n\n";
    os << "#include <cstdint>\n";
    os << "#include <cstring>\n\n";
}

void emit_enum(std::ostream& os, const EnumInfo& e) {
    const std::string name = sanitize_ident(e.name);
    os << "enum class " << name << " : int64_t {\n";
    for (const auto& m : e.members) {
        os << indent(1) << sanitize_ident(m.first) << " = " << m.second << ",\n";
    }
    os << "};\n\n";
}

void emit_struct(std::ostream& os, const StructInfo& s, bool include_padding) {
    const std::string name = sanitize_ident(s.name);
    os << "// Size: 0x" << std::hex << s.size << std::dec << "\n";
    os << "struct " << name;
    if (!s.super_name.empty() && s.super_name != "None")
        os << " : public " << sanitize_ident(s.super_name);
    os << " {\n";

    // Sort properties by offset
    auto props = s.properties;
    std::sort(props.begin(), props.end(),
              [](const PropertyInfo& a, const PropertyInfo& b) { return a.offset < b.offset; });

    int32_t cursor = 0;
    // If we have a super, we don't know its size precisely here — skip pad to first field
    if (!props.empty())
        cursor = props.front().offset;

    int pad_id = 0;
    for (const auto& p : props) {
        if (include_padding && p.offset > cursor) {
            const int32_t gap = p.offset - cursor;
            os << indent(1) << "uint8_t Pad_" << pad_id++ << "[0x" << std::hex << gap << std::dec
               << "]; // 0x" << std::hex << cursor << std::dec << "\n";
        }
        const std::string ty = map_property_cpp_type(p);
        os << indent(1) << ty << " " << sanitize_ident(p.name);
        if (p.array_dim > 1)
            os << "[" << p.array_dim << "]";
        os << "; // 0x" << std::hex << p.offset << std::dec << " (" << p.type_name << ")\n";
        const int32_t span = (p.size > 0 ? p.size : 1) * (p.array_dim > 0 ? p.array_dim : 1);
        cursor = p.offset + span;
    }

    if (include_padding && s.size > cursor && s.size - cursor < 0x10000) {
        os << indent(1) << "uint8_t Pad_end[0x" << std::hex << (s.size - cursor) << std::dec
           << "];\n";
    }

    if (!s.functions.empty()) {
        os << "\n" << indent(1) << "// Functions\n";
        for (const auto& f : s.functions) {
            os << indent(1) << "// " << sanitize_ident(f.name) << " (flags=0x" << std::hex
               << f.function_flags << std::dec << ", parms=" << static_cast<int>(f.num_parms)
               << ", size=0x" << std::hex << f.parms_size << std::dec << ")\n";
            if (f.func)
                os << indent(1) << "// native @ 0x" << std::hex << f.func << std::dec << "\n";
        }
    }

    os << "};\n\n";
}

std::string package_filename(const std::string& name) {
    std::string f = sanitize_ident(name);
    if (f.empty())
        f = "Package";
    return f + "_classes.hpp";
}

} // namespace

std::string sanitize_ident(const std::string& name) {
    if (name.empty())
        return "unnamed";
    std::string o;
    o.reserve(name.size());
    for (size_t i = 0; i < name.size(); ++i) {
        const char c = name[i];
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_')
            o.push_back(c);
        else
            o.push_back('_');
    }
    if (o[0] >= '0' && o[0] <= '9')
        o.insert(o.begin(), '_');
    // C++ keywords
    static const char* kws[] = {"class", "struct", "enum", "template", "operator", "private",
                                "public", "protected", "friend", "default", "delete", "new",
                                "float", "int", "bool", "char", "void", "this", "true", "false"};
    for (const char* k : kws) {
        if (o == k) {
            o += '_';
            break;
        }
    }
    return o;
}

std::string map_property_cpp_type(const PropertyInfo& p) {
    const std::string& t = p.type_name;
    auto has = [&](const char* s) { return t.find(s) != std::string::npos; };

    if (has("BoolProperty"))   return "bool";
    if (has("ByteProperty"))   return "uint8_t";
    if (has("Int8Property"))   return "int8_t";
    if (has("Int16Property"))  return "int16_t";
    if (has("IntProperty"))    return "int32_t";
    if (has("Int64Property"))  return "int64_t";
    if (has("UInt16Property")) return "uint16_t";
    if (has("UInt32Property")) return "uint32_t";
    if (has("UInt64Property")) return "uint64_t";
    if (has("FloatProperty"))  return "float";
    if (has("DoubleProperty")) return "double";
    if (has("NameProperty"))   return "FName";
    if (has("StrProperty"))    return "FString";
    if (has("TextProperty"))   return "FText";
    if (has("ObjectProperty") || has("ClassProperty") || has("WeakObjectProperty") ||
        has("SoftObjectProperty") || has("LazyObjectProperty"))
        return "void*"; // UObject*
    if (has("StructProperty")) return "uint8_t"; // opaque without inner type resolve
    if (has("ArrayProperty"))  return "TArray<uint8_t>";
    if (has("MapProperty"))    return "TMap<uint8_t,uint8_t>";
    if (has("SetProperty"))    return "TSet<uint8_t>";
    if (has("EnumProperty"))   return "uint8_t";
    if (has("DelegateProperty") || has("Multicast")) return "FScriptDelegate";
    if (has("InterfaceProperty")) return "void*";
    if (has("FieldPathProperty")) return "void*";

    if (p.size == 1) return "uint8_t";
    if (p.size == 2) return "uint16_t";
    if (p.size == 4) return "uint32_t";
    if (p.size == 8) return "uint64_t";
    return "uint8_t";
}

int write_offsets_header(const std::string& path,
                         const ue_offsets& offsets,
                         const ue_globals& globals,
                         const ue_version& version) {
    std::ofstream os(path, std::ios::binary);
    if (!os) {
        UE_LOG_E("Failed to write %s", path.c_str());
        return -1;
    }
    write_banner(os, "Engine offsets & globals");
    os << "namespace UEOffsets {\n\n";
    os << "constexpr int EngineMajor = " << version.major << ";\n";
    os << "constexpr int EngineMinor = " << version.minor << ";\n";
    os << "constexpr int EnginePatch = " << version.patch << ";\n\n";

    os << "namespace Globals {\n";
    os << "    constexpr uintptr_t GObjects     = 0x" << std::hex << globals.gobjects << std::dec << ";\n";
    os << "    constexpr uintptr_t GNames       = 0x" << std::hex << globals.gnames << std::dec << ";\n";
    os << "    constexpr uintptr_t GWorld       = 0x" << std::hex << globals.gworld << std::dec << ";\n";
    os << "    constexpr uintptr_t ProcessEvent = 0x" << std::hex << globals.process_event << std::dec << ";\n";
    os << "}\n\n";

    auto emit = [&](const char* n, int32_t v) {
        os << "    constexpr int32_t " << n << " = 0x" << std::hex << v << std::dec << ";\n";
    };

    os << "namespace UObject {\n";
    emit("VTable", offsets.uobject_vtable);
    emit("Flags", offsets.uobject_flags);
    emit("InternalIndex", offsets.uobject_internal_index);
    emit("Class", offsets.uobject_class);
    emit("Name", offsets.uobject_name);
    emit("Outer", offsets.uobject_outer);
    os << "}\n\n";

    os << "namespace UStruct {\n";
    emit("Super", offsets.ustruct_super);
    emit("Children", offsets.ustruct_children);
    emit("ChildProperties", offsets.ustruct_child_properties);
    emit("Size", offsets.ustruct_size);
    emit("MinAlignment", offsets.ustruct_min_alignment);
    os << "}\n\n";

    os << "namespace UClass {\n";
    emit("CastFlags", offsets.uclass_cast_flags);
    emit("DefaultObject", offsets.uclass_default_object);
    os << "}\n\n";

    os << "namespace UFunction {\n";
    emit("FunctionFlags", offsets.ufunction_function_flags);
    emit("NumParms", offsets.ufunction_num_parms);
    emit("ParmsSize", offsets.ufunction_parms_size);
    emit("ReturnValueOffset", offsets.ufunction_return_value_offset);
    emit("Func", offsets.ufunction_func);
    os << "}\n\n";

    os << "namespace FField {\n";
    emit("Class", offsets.ffield_class);
    emit("Owner", offsets.ffield_owner);
    emit("Next", offsets.ffield_next);
    emit("Name", offsets.ffield_name);
    emit("Flags", offsets.ffield_flags);
    os << "}\n\n";

    os << "namespace FProperty {\n";
    emit("ArrayDim", offsets.property_array_dim);
    emit("ElementSize", offsets.property_element_size);
    emit("PropertyFlags", offsets.property_property_flags);
    emit("Offset", offsets.property_offset);
    os << "}\n\n";

    os << "namespace FUObjectArray {\n";
    emit("Objects", offsets.fuobjectarray_objects);
    emit("NumElements", offsets.fuobjectarray_num_elements);
    emit("MaxElements", offsets.fuobjectarray_max_elements);
    emit("NumChunks", offsets.fuobjectarray_num_chunks);
    emit("ItemSize", offsets.fuobjectitem_size);
    emit("ItemObject", offsets.fuobjectitem_object);
    os << "    constexpr int ObjectsChunked = " << offsets.objects_chunked << ";\n";
    os << "    constexpr int ElementsPerChunk = " << std::dec << offsets.objects_elements_per_chunk << ";\n";
    os << "}\n\n";

    os << "namespace Features {\n";
    os << "    constexpr int UsesNamePool = " << offsets.uses_name_pool << ";\n";
    os << "    constexpr int UsesFField   = " << offsets.uses_ffield << ";\n";
    os << "}\n\n";

    os << "} // namespace UEOffsets\n";
    return 1;
}

int generate_cpp_sdk(const std::vector<PackageInfo>& packages,
                     const ue_offsets& offsets,
                     const ue_globals& globals,
                     const ue_version& version,
                     const GenerateOptions& options) {
    std::error_code ec;
    fs::create_directories(options.output_dir, ec);
    if (ec) {
        UE_LOG_E("Cannot create output dir: %s", options.output_dir.c_str());
        return -1;
    }

    int files = 0;
    if (options.write_offsets_header) {
        const auto path = (fs::path(options.output_dir) / "Offsets.hpp").string();
        if (write_offsets_header(path, offsets, globals, version) > 0)
            ++files;
    }

    // Basic types header
    {
        const auto path = (fs::path(options.output_dir) / "BasicTypes.hpp").string();
        std::ofstream os(path, std::ios::binary);
        if (os) {
            write_banner(os, "BasicTypes");
            os << "struct FName {\n"
                  "    int32_t ComparisonIndex;\n"
                  "    int32_t Number;\n"
                  "};\n\n"
                  "struct FString {\n"
                  "    wchar_t* Data;\n"
                  "    int32_t  Num;\n"
                  "    int32_t  Max;\n"
                  "};\n\n"
                  "struct FText { uint8_t opaque[0x18]; };\n\n"
                  "struct FScriptDelegate { uint8_t opaque[0x10]; };\n\n"
                  "template<typename T>\n"
                  "struct TArray {\n"
                  "    T*      Data;\n"
                  "    int32_t Num;\n"
                  "    int32_t Max;\n"
                  "};\n\n"
                  "template<typename K, typename V>\n"
                  "struct TMap { uint8_t opaque[0x50]; };\n\n"
                  "template<typename T>\n"
                  "struct TSet { uint8_t opaque[0x50]; };\n\n";
            ++files;
        }
    }

    std::ofstream sdk_all;
    const auto sdk_path = (fs::path(options.output_dir) / "SDK.hpp").string();
    sdk_all.open(sdk_path, std::ios::binary);
    if (sdk_all) {
        write_banner(sdk_all, "SDK umbrella");
        sdk_all << "#include \"BasicTypes.hpp\"\n";
        sdk_all << "#include \"Offsets.hpp\"\n\n";
    }

    for (const auto& pkg : packages) {
        if (pkg.classes.empty() && pkg.structs.empty() && pkg.enums.empty())
            continue;

        const std::string fname = package_filename(pkg.name);
        const auto path = (fs::path(options.output_dir) / fname).string();
        std::ofstream os(path, std::ios::binary);
        if (!os) {
            UE_LOG_W("Skip write %s", path.c_str());
            continue;
        }
        write_banner(os, "Package: " + pkg.name);
        os << "#include \"BasicTypes.hpp\"\n\n";
        os << "// Package: " << pkg.name << "\n\n";

        for (const auto& e : pkg.enums)
            emit_enum(os, e);
        for (const auto& s : pkg.structs)
            emit_struct(os, s, options.include_padding);
        for (const auto& c : pkg.classes)
            emit_struct(os, c, options.include_padding);

        ++files;
        if (sdk_all)
            sdk_all << "#include \"" << fname << "\"\n";
        UE_LOG_D("Wrote %s (%zu classes, %zu structs, %zu enums)",
                 fname.c_str(), pkg.classes.size(), pkg.structs.size(), pkg.enums.size());
    }

    if (sdk_all)
        ++files;

    UE_LOG_I("C++ generator wrote %d files to %s", files, options.output_dir.c_str());
    return files;
}

} // namespace ue
